//
//  ViewController.swift
//  tableView example
//
//  Created by jose sanchez on 8/4/20.
//  Copyright © 2020 jose sanchez. All rights reserved.
//

import UIKit

class ViewController: UIViewController, UITableViewDelegate, UITableViewDataSource {
    let image = UIImage(named: "movieIcon")
    
    let listItems = [
    "Snow White and the Seven Dwarfs",
    "Pinocchio",
    "Fantasia",
    "Song of the South",
    "Cinderella",
    "20,000 Leagues Under the Sea",
    "Lady and the Tramp",
    "Sleeping Beauty",
    "101 Dalmatians",
    "The Absent Minded Professor",
    "Babes in Toyland",
    "Bon Voyage!",
    "The Sword in the Stone",
    "The Jungle Book",
    "Blackbeard's Ghost",
    "The Aristocats",
    "The Boatniks",
    "Bedknobs and Broomsticks",
    "The Apple Dumpling Gang",
    "Freaky Friday",
    "The Many Adventures of Winnie the Pooh",
    "The Rescuers",
    "Herbie Goes to Monte Carlo",
    "The Black Hole",
    "Midnight Madness",
    "The Last Flight of Noah’s Ark",
    "The Devil and Max Devlin",
    "Amy",
    "The Fox and the Hound",
    "Condorman",
    "Night Crossing",
    "Tron",
    "Tex",
    "Trenchcoat",
    "Something Wicked This Way Comes",
    "Never Cry Wolf",
    "Running Brave",
    "Splash",
    "Country",
    "Baby: Secret of the Lost Legend",
    "Return to Oz",
    "The Black Cauldron",
    "My Science Project",
    "The Journey of Natty Gann",
    "One Magic Christmas",
    "Down and Out in Beverly Hills",
    "Off Beat",
    "Ruthless People",
    "The Great Mouse Detective",
    "Flight of the Navigator",
    "Tough Guys",
    "The Color of Money",
    "Outrageous Fortune",
    "Tin Men",
    "Ernest Goes to Camp",
    "Benji the Hunted",
    "Adventures in Babysitting",
    "Stakeout",
    "Can't Buy Me Love",
    "Hello Again",
    "3 Men and a Baby",
    "Good Morning Vietnam",
    "Shoot to Kill",
    "D.O.A.",
    "Return to Snowy River",
    "Big Business",
    "Who Framed Roger Rabbit?",
    "Cocktail",
    "The Rescue",
    "Heartbreak Hotel",
    "The Good Mother",
    "Ernest Saves Christmas",
    "Oliver & Company",
    "Beaches",
    "Three Fugitives",
    "New York Stories",
    "Disorganized Crime",
    "Dead Poets Society",
    "Honey, I Shrunk the Kids",
    "Turner & Hooch",
    "Cheetah",
    "An Innocent Man",
    "Gross Anatomy",
    "The Little Mermaid",
    "Blaze",
    "Stella",
    "Where the Heart Is",
    "Pretty Woman",
    "Ernest Goes to Jail",
    "Spaced Invaders",
    "Fire Birds",
    "Dick Tracy",
    "Betsy's Wedding",
    "Arachnophobia",
    "DuckTales: The Movie - Treasure of th…",
    "Taking Care of Business",
    "Mr. Destiny",
    "The Rescuers Down Under",
    "3 Men and a Little Lady",
    "Green Card",
    "White Fang",
    "Scenes from a Mall",
    "Haakon Haakonsen",
    "The Marrying Man",
    "Oscar",
    "One Good Cop",
    "What About Bob?",
    "Wild Hearts Can't Be Broken",
    "The Rocketeer",
    "The Doctor",
    "Paradise",
    "Deceived",
    "Ernest Scared Stupid",
    "Billy Bathgate",
    "Beauty and the Beast",
    "Father of the Bride",
    "The Hand That Rocks the Cradle",
    "Medicine Man",
    "Blame it on the Bellboy",
    "Noises Off...",
    "Straight Talk",
    "Newsies",
    "Passed Away",
    "Encino Man",
    "Sister Act",
    "Honey I Blew Up the Kid",
    "A Stranger Among Us",
    "3 Ninjas",
    "A Gun in Betty Lou's Handbag",
    "Captain Ron",
    "Sarafina!",
    "Innocent Blood",
    "The Mighty Ducks",
    "1492: Conquest of Paradise",
    "Consenting Adults",
    "Aladdin",
    "The Distinguished Gentleman",
    "The Muppet Christmas Carol",
    "Alive",
    "Aspen Extreme",
    "Homeward Bound: The Incredible Journey",
    "The Cemetery Club",
    "Swing Kids",
    "A Far Off Place",
    "Born Yesterday",
    "The Adventures of Huck Finn",
    "Bound by Honor",
    "Indian Summer",
    "Super Mario Bros.",
    "Guilty as Sin",
    "Life With Mikey",
    "What's Love Got to Do With It",
    "Son in Law",
    "Hocus Pocus",
    "Another Stakeout",
    "My Boyfriend's Back",
    "Father Hood",
    "The Joy Luck Club",
    "Money for Nothing",
    "The Program",
    "Cool Runnings",
    "The Nightmare Before Christmas",
    "The Three Musketeers",
    "Sister Act 2 Back in the Habit",
    "Tombstone",
    "The Air Up There",
    "Cabin Boy",
    "Iron Will",
    "Red Rock West",
    "Blank Check",
    "Angie",
    "The Ref",
    "D2: The Mighty Ducks",
    "Holy Matrimony",
    "White Fang 2: Myth of the White Wolf",
    "The Inkwell",
    "When a Man Loves a Woman",
    "3 Ninjas Kick Back",
    "Renaissance Man",
    "The Lion King",
    "I Love Trouble",
    "Angels in the Outfield",
    "In the Army Now",
    "Color of Night",
    "Camp Nowhere",
    "It's Pat",
    "A Simple Twist of Fate",
    "Quiz Show",
    "Terminal Velocity",
    "Ed Wood",
    "The Puppet Masters",
    "Squanto: A Warrior's Tale",
    "The Santa Clause",
    "A Low Down Dirty Shame",
    "The Jungle Book",
    "Houseguest",
    "Bad Company",
    "Miami Rhapsody",
    "The Jerky Boys",
    "Heavy Weights",
    "Man of the House",
    "Roommates",
    "Tall Tale",
    "A Pyromaniac's Love Story",
    "Jefferson in Paris",
    "Funny Bones",
    "A Goofy Movie",
    "While You Were Sleeping",
    "Crimson Tide",
    "Mad Love",
    "Pocahontas",
    "Judge Dredd",
    "Operation Dumbo Drop",
    "Dangerous Minds",
    "A Kid in King Arthur's Court",
    "The Tie That Binds",
    "Unstrung Heroes",
    "The Big Green",
    "Dead Presidents",
    "The Scarlet Letter",
    "Feast of July",
    "Powder",
    "Toy Story",
    "Father of the Bride Part II",
    "Nixon",
    "Tom and Huck",
    "Mr. Holland's Opus",
    "White Squall",
    "Muppet Treasure Island",
    "Mr. Wrong",
    "Before and After",
    "Up Close & Personal",
    "Homeward Bound II: Lost in San Franc…",
    "Two Much",
    "Un indien dans la ville",
    "James and the Giant Peach",
    "Celtic Pride",
    "Last Dance",
    "Boys",
    "Spy Hard",
    "Eddie",
    "The Rock",
    "The Hunchback of Notre Dame",
    "Phenomenon",
    "Kazaam",
    "Jack",
    "First Kid",
    "The Rich Man's Wife",
    "D3: The Mighty Ducks",
    "The Associate",
    "Ransom",
    "The War at Home",
    "101 Dalmatians",
    "The Preacher's Wife",
    "Evita",
    "Metro",
    "Prefontaine",
    "Shadow Conspiracy",
    "That Darn Cat",
    "Jungle 2 Jungle",
    "The Sixth Man",
    "Grosse Pointe Blank",
    "Romy and Michele's High School Reunion",
    "Gone Fishin'",
    "Con Air",
    "Hercules",
    "George Of The Jungle",
    "Nothing To Lose",
    "Air Bud",
    "G.I. Jane",
    "A Thousand Acres",
    "Washington Square",
    "Rocket Man",
    "Playing God",
    "Flubber",
    "An American Werewolf in Paris",
    "Mr. Magoo",
    "Kundun",
    "Deep Rising",
    "Krippendorf's Tribe",
    "An Alan Smithee Film: Burn Hollywood …",
    "Meet the Deedles",
    "He Got Game",
    "The Horse Whisperer",
    "Six Days, Seven Nights",
    "Mulan",
    "Armageddon",
    "Jane Austen's Mafia",
    "The Parent Trap",
    "Firelight",
    "Simon Birch",
    "Holy Man",
    "Beloved",
    "The Waterboy",
    "I'll Be Home For Christmas",
    "A Bug's Life",
    "Enemy of the State",
    "Rushmore",
    "A Civil Action",
    "Mighty Joe Young",
    "My Favorite Martian",
    "The Other Sister",
    "Doug's 1st Movie",
    "Ten Things I Hate About You",
    "Endurance",
    "Instinct",
    "Tarzan",
    "Summer of Sam",
    "Inspector Gadget",
    "The Sixth Sense",
    "The 13th Warrior",
    "Breakfast of Champions",
    "Mumford",
    "Mystery, Alaska",
    "The Straight Story",
    "The Insider",
    "Toy Story 2",
    "Cradle Will Rock",
    "Deuce Bigalow: Male Gigolo",
    "Bicentennial Man",
    "Play it to the Bone",
    "Fantasia 2000 (IMAX)",
    "Gun Shy",
    "The Tigger Movie",
    "Mission to Mars",
    "High Fidelity",
    "Keeping the Faith",
    "Dinosaur",
    "Shanghai Noon",
    "Gone in 60 Seconds",
    "Fantasia 2000 (Theatrical Release)",
    "The Kid",
    "Coyote Ugly",
    "The Crew",
    "Duets",
    "Remember the Titans",
    "Unbreakable",
    "102 Dalmatians",
    "The Emperor's New Groove",
    "O Brother, Where Art Thou?",
    "Double Take",
    "Recess: School's Out",
    "Just Visiting",
    "Pearl Harbor",
    "Atlantis: The Lost Empire",
    "crazy/beautiful",
    "The Princess Diaries",
    "Bubble Boy",
    "Max Keeble's Big Move",
    "Corky Romano",
    "High Heels and Low Lifes",
    "Monsters, Inc.",
    "Out Cold",
    "The Royal Tenenbaums",
    "Beauty and the Beast (IMAX)",
    "Frank McKlusky C.I.",
    "Snow Dogs",
    "The Count of Monte Cristo",
    "Peter Pan: Return to Neverland",
    "Reign of Fire",
    "Sorority Boys",
    "The Rookie",
    "Big Trouble",
    "ESPN's Ultimate X - The Movie",
    "Bad Company",
    "Lilo & Stitch",
    "The Country Bears",
    "Signs",
    "Sen to Chihiro no Kamikakushi",
    "Sweet Home Alabama",
    "Moonlight Mile",
    "Tuck Everlasting",
    "The Santa Clause 2",
    "Treasure Planet",
    "The Hot Chick",
    "25th Hour",
    "The Recruit",
    "Shanghai Knights",
    "The Jungle Book 2",
    "Bringing Down the House",
    "Piglet's Big Movie",
    "Ghosts of the Abyss",
    "Holes",
    "The Lizzie McGuire Movie",
    "Finding Nemo",
    "Pirates of the Caribbean: The Curse o…",
    "Freaky Friday",
    "Open Range",
    "Cold Creek Manor",
    "Under the Tuscan Sun",
    "Veronica Guerin",
    "Brother Bear",
    "The Haunted Mansion",
    "Calendar Girls",
    "Young Black Stallion",
    "Teacher's Pet: The Movie",
    "Miracle",
    "Confessions of a Teenage Drama Queen",
    "Hidalgo",
    "The Ladykillers",
    "Home on the Range",
    "The Alamo",
    "Raising Helen",
    "Around the World in 80 Days",
    "America's Heart and Soul",
    "King Arthur",
    "The Village",
    "The Princess Diaries 2: Royal Engagement",
    "Mr. 3000",
    "The Last Shot",
    "Ladder 49",
    "The Incredibles",
    "National Treasure",
    "The Life Aquatic with Steve Zissou",
    "Aliens of the Deep",
    "Pooh's Heffalump Movie",
    "The Pacifier",
    "Ice Princess",
    "A Lot Like Love",
    "The Hitchhiker's Guide to the Galaxy",
    "Hauru no ugoku shiro",
    "Herbie: Fully Loaded",
    "Dark Water",
    "Sky High",
    "Valiant",
    "Flightplan",
    "The Greatest Game Ever Played",
    "Shopgirl",
    "Chicken Little",
    "The Chronicles of Narnia: The Lion, t…",
    "Casanova",
    "Glory Road",
    "Annapolis",
    "Roving Mars",
    "Eight Below",
    "The Shaggy Dog",
    "Stay Alive",
    "The Wild",
    "Stick It",
    "Goal! The Dream Begins",
    "Cars",
    "Pirates of the Caribbean: Dead Man’…",
    "Step Up",
    "Invincible",
    "The Guardian",
    "The Prestige",
    "Tim Burton's The Nightmare Before Chr…",
    "The Santa Clause 3: The Escape Clause",
    "Déjà Vu",
    "Apocalypto",
    "Primeval",
    "Bridge to Terabithia",
    "Wild Hogs",
    "Meet the Robinsons",
    "The Lookout",
    "The Hoax",
    "The Invisible",
    "Pirates of the Caribbean: At World’…",
    "Ratatouille",
    "Underdog",
    "The Game Plan",
    "Dan in Real Life",
    "Enchanted",
    "National Treasure 2: Book of Secrets",
    "Hannah Montana/Miley Cyrus: Best of B…",
    "Step Up 2 the Streets",
    "College Road Trip",
    "The Chronicles of Narnia: Prince Caspian",
    "WALL-E",
    "Swing Vote",
    "Goal! 2: Living the Dream...",
    "Miracle at St. Anna",
    "Beverly Hills Chihuahua",
    "Morning Light",
    "High School Musical 3: Senior Year",
    "Bolt",
    "Bedtime Stories",
    "Confessions of a Shopaholic",
    "Jonas Brothers: The 3D Concert Experi…",
    "Race to Witch Mountain",
    "Hannah Montana the Movie",
    "Earth",
    "Up",
    "The Proposal",
    "G-Force",
    "Gake no ue no Ponyo",
    "X Games 3D: The Movie",
    "Walt and El Grupo",
    "Surrogates",
    "Toy Story 3D Double Feature",
    "Disney's A Christmas Carol",
    "The Princess and the Frog",
    "Old Dogs",
    "When in Rome",
    "Alice in Wonderland",
    "Waking Sleeping Beauty",
    "The Last Song",
    "Oceans",
    "Prince of Persia: Sands of Time",
    "Toy Story 3",
    "The Sorcerer's Apprentice",
    "Step Up 3D",
    "Gedo Senki (Tales from Earthsea)",
    "You Again",
    "Secretariat",
    "Tangled",
    "Tron: Legacy",
    "Gnomeo and Juliet",
    "I am Number Four",
    "Mars Needs Moms",
    "African Cats",
    "Zokkomon",
    "Prom",
    "Pirates of the Caribbean: On Stranger…",
    "Cars 2",
    "Winnie the Pooh",
    "The Help",
    "Fright Night",
    "Real Steel",
    "The Muppets",
    "War Horse",
    "The Secret World of Arietty",
    "John Carter",
    "Chimpanzee",
    "The Avengers",
    "Brave",
    "People Like Us",
    "The Odd Life of Timothy Green",
    "Frankenweenie",
    "Wreck-It Ralph",
    "Lincoln",
    "Oz the Great and Powerful",
    "Iron Man 3",
    "Monsters University",
    "The Lone Ranger",
    "Disney Planes",
    "The Fifth Estate",
    "Thor: The Dark World",
    "Kaze Tachinu",
    "Frozen",
    "Delivery Man",
    "Saving Mr. Banks",
    "Need for Speed",
    "Muppets Most Wanted",
    "Captain America: The Winter Soldier",
    "Bears",
    "Million Dollar Arm",
    "Maleficent",
    "Planes: Fire and Rescue",
    "Guardians of the Galaxy",
    "The Hundred-Foot Journey",
    "Alexander and the Terrible, Horrible,…",
    "Big Hero 6",
    "Into the Woods",
    "Strange Magic",
    "McFarland, USA",
    "Cinderella",
    "Monkey Kingdom",
    "Avengers: Age of Ultron",
    "Tomorrowland",
    "Inside Out",
    "Ant-Man",
    "Bridge of Spies",
    "The Good Dinosaur",
    "Star Wars Ep. VII: The Force Awakens",
    "The Finest Hours",
    "Zootopia",
    "The Jungle Book",
    "A Beautiful Planet",
    "Captain America: Civil War",
    "Alice Through the Looking Glass",
    "Finding Dory",
    "The BFG",
    "Pete’s Dragon",
    "The Light Between Oceans",
    "Queen of Katwe",
    "Doctor Strange",
    "Moana",
    "Rogue One: A Star Wars Story"
    ]
    
    override func viewDidLoad() {
        super.viewDidLoad()
        // Do any additional setup after loading the view.
    }
    func tableView(_ tableView: UITableView, numberOfRowsInSection section: Int) -> Int {
        return listItems.count
    }
    func tableView(_ tableView: UITableView, cellForRowAt indexPath: IndexPath) -> UITableViewCell {
        let cell = tableView.dequeueReusableCell(withIdentifier: "initialCell")
        cell?.textLabel?.text = listItems[indexPath.row]
        cell?.imageView?.image = image
        return cell!
    }
    
    func tableView(_ tableView: UITableView, didSelectRowAt indexPath: IndexPath) {
        
        let title = indexPath.row == 563 ? "is actually pretty cool" : "sucks!"
        let message = indexPath.row == 563 ? "is actually not too bad." : "is terrible. Shame on you!"
        let buttonText = indexPath.row == 563 ? "Yay 😌" : "No it doesn't 😢"
        
        let alertView = UIAlertController(title: "Your movie \(title)", message: "Your movie, \(listItems[indexPath.row]), \(message)", preferredStyle: UIAlertController.Style.alert)
        alertView.addAction(UIAlertAction(title: buttonText, style: UIAlertAction.Style.cancel, handler: nil))
        self.present(alertView, animated: true, completion: nil)
    }
    
}

